### PR TITLE
Set up firebase and create models

### PR DESCRIPTION
**Pull request by lsunxh**

### CODE REVIEW

**Review by Emily-Feng — APPROVED** [review]

**Comment by Emily-Feng** [comment]
LGTM

**Comment by lsunxh** [comment]
I changed the app structure name to match the app name. Hopefully this fixes the conflict.

**Comment by Emily-Feng** [comment]
Still merge conflicts there. try create a gitignore file and add .DS_store in it
and use command line to resolve the conflicts

**Comment by lsunxh** [comment]
I added git ignore, but not sure why it's not doing its job.

**Pull request closed without merging**
